language: node_js
node_js:
- '4.3'
install:
- npm install
before_script:
- chmod +x deploy.sh
sudo: false
deploy:
- provider: script
  skip_cleanup: true
  script: "./deploy.sh"
  on:
    branch: dev
- provider: script
  skip_cleanup: true
  script: "./deploy.sh"
  on:
    branch: release
- provider: script
  skip_cleanup: true
  script: "./deploy.sh"
  on:
    branch: master
env:
  matrix:
  - CXX=g++-4.8
  global:
  - secure: hDA7g7jYdBkFyLcRyHJL6hvZS1Rvh5d0yzzC4Hi+j5r1HYg7cqnAs4VwEhEV7Y4C9FBvDK43YXtQuQ8GSTYXVjJQQwgcJ+efHihKCfIrtSOW4x2WEZx2BhoiSAv3QkS/Krq8VEd/Zgf/OuKJjUqQUe4cLZurcCNqWc8DB9Ytbtr7RM8ozn/O5KN9l91/wBMUNZrwvUp8ro6SXlUUAzRritu+hhACUmoY5a5kxqgvMZPuzIurmj4z1mq7nyYKk+Sj4NQ6pQD3gd2vU2OEfKxsPDDLjPSCnObrCWtdBya/jzpPjCIWnTxgakSWQa6g6386ToRa8eZGi4DCKTvKfR3IucOSb2yNccVVY/xHsmnazmpSb2wNhIvnK5Q5SpTYMMPWmJdz9dlxT0spo3LFO5DYlHNuUPtV9gq+TzoUWIVVT67MhFBYoOEU7aRxGBLr3YNonKH6kWwmTRT/5y9V+X2AK9YPw55Ft5kw3mX4n8AzOOmsi+nAC07xvMSpzOTFuTaVr+QemvCV13kbAHCN4Xt+h06KjK3ceMpXabL2VbuJPwXp0sbFE4WGaok2MMBSmB58Hcovwqs7OEOIKqAJEWsTXp3DyJxbPZ9twtqZMj5gK+TEgRObkD4F5QbRbAJKoJbvBj8X1C/NaOxt9KsH1/dGn1ISrjvDckAibt4LyqL7n8M=
  - secure: evHyyqlB/lgx9lHr7gfcMI3zabOSoLi06A2KbIPfm1ynTupIdVf/oKNHy4S95WEcHWFKBmcOljvdoSU4cWvGUgbVAXgPgOihnmwUDa3rwus12FxACKpnZZCktGm/azgYTZjo3jzyWQkpgD2o341wvPKhK+DsplnP5Kg6PFpLKyyUPkpWxe2BP/X0fOu3P1Nv9L/sYykA6Uy6dCMqTy6YJeUL3qdfrzXbryzcjY76/dES1ztJSMqpU0YBJct9m5tCCy2AzyCGvQujA17JnTackMigtz+EPr8rQByPtLvh79vEPtnn6iad7ZL8es+Lf6FIiJkS9qlGZDifqhSa7CL57iSyAbV28Vk43Kv9Vt+RIG2dqRw/t0faszz278kMmgZFwe3lCsvlVcLACYx0GMcXYIJwLK8/Ct7FNVwuBkdaGRJLdKg3WeI9PNBfBl/Ri7sp4buAmA4IeBCpygUihxL8HALU9tTGx3n/tkn0p7VZnknZ/zndg7SghCW68L7Mcfpca3y2EOOUQ4I9mT/sLv5vJ7aSSEk0jTiC0NQEIYfaw5rZMENwHPjsj+mdcVw9EeTVY8WNsYZPhhecAaqzPT4IkD4M59ur7C58iLGrKVPbTi5ywz01Cis+5Nj480mAFkvJc+hSGLa5VqrFI8GUD+95Z9JwzD1/BKCZjCvCrUOiN2I=
  - secure: MgrHW/Hdyf3NdBKQpQaYJaOd4hUe++RrudEHnimmCoB63VVUlpbwklgAvwm2oG+VmlXdbqzNB0A4idYIkRXczc8/XHammshQIvMFK3eYesMkHnmXRfNoA5OnKPu5p05u276izFTEVH1oPgE0Q/R9Ltp2LRe5If8Mj2+1J+uc4j6N8TBw8+SdB9X+8HdbU8RVmjVFuuX/mmBOSONxlpwqDJ0ER5iMiTPuUN2d8c6r3bVzgzyl3tJFqJAXUOdvUfvONvtTw/wfXw3QF0/2J+V2F9zfTCy4e3pul2TU/IqkyPJdPnboPoMJ+RwOX+UUA7Wu5FOQdcdQfQhyi/TDOQx8vkuvv/W4GGSkdeIt8vkWQ4tCUS7v88qXY16TpVFUhar2TJMmaGD/WR26vIK8EM7X+Kytr6mZGPKJ0TjspxIj5l3j1Jl5+Cm7B5gutG7lRK4xrcr0klzQ3NYIqB9lxd0hCJR9fAfKKP9Keuee+PhVe9GIOWQIs/PluFO+mK4uYVaVFAT4P8n48W/QoxN3MyFbQMtebEGRyXF4pis7sDUq6DuwYcqubndy68xEqMe/1ATgakJ1hmBEURExw2RtQ2I5QOEZo+R8YNnZLqw9L1X7um6DTAOT9fQE5xYJVM9En2uwNaNhn75MofL7LZxwEg3vamAnUyMAuX1lxm0xQi+p/qg=
notifications:
  slack:
    secure: PMGlpdBoRzMlIjCsPWdXJ1wf550b+mpX0x44ggGWNL7ErpNebfyqIbXf4VJXYQDmhVJt31ygDaxTtj8XwZJlbvQjE6WGHU26KvL/efGJJL5EmgFD8LDBFpsbn49PyoZuVOTbSzqP8d8WCCPo4oBvX2r2Q2Ixh/tUx7i4Bcv0XwNpWAR75v1Yq/NftEI48k2GcI3oHqmuEgLHdP93k1rCUM4sBsgkr4PCltZfoE2AWlF6wY59w/oFiKj4FwycY8QjJZa/zbSQq1B/9QD7n4YBY4QjVv3LmjshEiQv1HGo2rNLV+/BB5ZoQ6JEH9h+seduHNTF+mkToKbJ2YjDERLlqLFYWVQKXTqFkSdYuknguJ3uOfXFaGtPDSqTRljE6WW6UDIJi9lDpxFHjH2q848/2O03RKtYeFKJWNbVb7Q2PWTBFxx6OurYra+tbUAorQiYmAQxd0vJY+qzGIDJZIQ8yDE4C10heOhfRyU8wJSKF3xJUKKWVGfBuHivFBZOETFSg0uVBcJnsXRcErvEQz0LuKaZfP81bIokcKUGxum/xyp9mYhYqWDvIj31RUhDMiRxXTPe9PhW0mlOtRG7tm2+8G08exHPSfONSV2IPUtlQt4j2/+I22ncOwtsm6yZzXXbDjoMR2sCHIyJj3lVECOqAnCfNJ6Q0CNJ93LqxKSHdFU=
