#!/bin/bash
if [ "$TRAVIS_BRANCH" = "dev" ]; then
  export MAILCHIMP_API_KEY=$DEV_MAILCHIMP_API_KEY
  export TOPCODER_MAILING_LIST_ID=$DEV_TOPCODER_MAILING_LIST_ID
  export AWS_LAMBDA_ROLE_ARN=$DEV_AWS_LAMBDA_ROLE_ARN
elif [ "$TRAVIS_BRANCH" = "release" ]; then
  export MAILCHIMP_API_KEY=$QA_MAILCHIMP_API_KEY
  export TOPCODER_MAILING_LIST_ID=$QA_TOPCODER_MAILING_LIST_ID
  export AWS_LAMBDA_ROLE_ARN=$QA_AWS_LAMBDA_ROLE_ARN
elif [ "$TRAVIS_BRANCH" = "master" ]; then
  export MAILCHIMP_API_KEY=$PROD_MAILCHIMP_API_KEY
  export TOPCODER_MAILING_LIST_ID=$PROD_TOPCODER_MAILING_LIST_ID
  export AWS_LAMBDA_ROLE_ARN=$PROD_AWS_LAMBDA_ROLE_ARN
fi

./node_modules/.bin/gulp deploy